"""Initial migration.

Revision ID: 983cbcebdc83
Revises: 
Create Date: 2024-07-29 18:26:56.589751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983cbcebdc83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_due', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('time_due')

    # ### end Alembic commands ###
